languages:
        "EN":
                greeting: "Welcome to JokerCord v2 SelfBot."
                emptytoken: "Your token is empty."
                running: "JokerCord is connected and running. Version: "
                error: "An error has ocurred."
                tokenprompt: "Please enter your token: "
                tokenerror: "It seems like your token is wrong."
                fileerror: "A file couldn't be loaded."
        "SP":
                greeting: "Bienvenido al SelfBot JokerCord v2."
                emptytoken: "Parece que tu token está vacío"
                running: "JokerCord está conectado y en ejecución. Versión: "
                error: "Ha ocurrido un error."
                tokenprompt: "Por favor introduce tu token: "
                tokenerror: "Parece que tu token está mal."
                fileerror: "Un archivo no pudo ser cargado."
        "DE":
                greeting: "Willkommen bei JokerCord v2 SelfBot"
                emptytoken: "Your token is empty."
        "FR":
                greeting: "Bienvenue sur JokerCord v2 SelfBot"
                emptytoken: "Your token is empty."
        "GK":
                greeting: "Καλώς ήλθατε στο JokerCord v2 SelfBot."
                emptytoken: "Your token is empty."
