languages:
        "EN":
                greeting: "Welcome to JokerCord v2 SelfBot."
                emptytoken: "Your token is empty."
                running: "JokerCord is connected and running."
                error: "An error has ocurred."
                tokenprompt: "Please enter your token: "
                tokenerror: "It seems like your token is wrong."
                fileerror: "A file couldn't be loaded."
        "ES":
                greeting: "Bienvenido al SelfBot JokerCord v2."
                emptytoken: "Parece que tu token está vacío"
                running: "JokerCord está conectado y en ejecución."
                error: "Ha ocurrido un error."
                tokenprompt: "Por favor introduce tu token: "
                tokenerror: "Parece que tu token está mal."
                fileerror: "Un archivo no pudo ser cargado."
        "DE":
                greeting: "Willkommen bei JokerCord v2 SelfBot"
                emptytoken: "Dein Token ist leer"
                running: "JokerCord ist verbunded und läuft."
                error: "Ein Fehler ist aufgetreten."
                tokenprompt: "Bitte füg dein Token ein: "
                tokenerror: "Dein Token ist falsch."
                fileerror: "Datei kann nich geladen werden."
        "FR":
                greeting: "Bienvenue sur le bot JokerCord v2"
                emptytoken: "Le token est manquant."
                running: "JokerCord est connecté est lancé"
                error: "Une erreur s'est produite."
                tokenprompt: "S'il vous plaît entrer votre token: "
                tokenerror: "Votre token est incorrecte."
                fileerror: "Le fichier n'a pas pu être chargé!"
        "NL":
                greeting: "Welkom bij JokerCord v2 zelfbot"
                emptytoken: "Uw token is leeg."
                running: "JokerCord is verbonded en actief"
                error: "Er is een fout opgetreden"
                tokenprompt: "Voer uw token in: "
                tokenerror: "Het lijkt erop dat uw token niet klopt"
                fileerror: "Eem bestand kon niet worden geladen"
        "EL":
                greeting: "Καλώς ήλθατε στο JokerCord v2 SelfBot."
                emptytoken: "Your token is empty."
